trigger:
- master
- topic-collNotes-v2
variables:
  buildConfiguration: 'Release'
  collNotesRepoName: 'j-h-m/collNotes'

stages:
- stage: Build
  jobs:
  - job: Android_App
    pool:
      vmImage: 'windows-latest'
    steps:
      - task: NuGetToolInstaller@1
        displayName: 'Install NuGet 5.x'
        inputs:
          versionSpec: '5.x'
          checkLatest: true
      - task: NuGetCommand@2
        displayName: 'NuGet restore'
        inputs:
          restoreSolution: '**/*.sln'
      - task: DotNetCoreCLI@2
        displayName: 'dotnet test on test project'
        inputs:
          command: test
          projects: '**/*Tests/*.csproj'
          arguments: '--configuration $(buildConfiguration)'
      - task: XamarinAndroid@1
        displayName: 'Build Android App'
        inputs:
          clean: true
          projectFile: '**/*droid*.csproj'
          outputDirectory: '$(Build.ArtifactStagingDirectory)'
          configuration: '$(buildConfiguration)'
          createAppPackage: true
      - task: AndroidSigning@3
        inputs:
          apkFiles: '**/*.apk'
          apksignerKeystoreFile: 'ad-hoc jacob.keystore'
          apksignerKeystorePassword: '$(apkSignerKeystorePassword)'
          apksignerKeystoreAlias: '$(keyStoreAlias)'
          apksignerKeyPassword: '$(keyPassword)'
      - task: GitHubRelease@1
        inputs:
          gitHubConnection: 'j-h-m'
          repositoryName: '$(collNotesRepoName)'
          action: 'create'
          tag: 'v2.x'
          tagSource: 'gitTag'
          title: 'test apk release'
          isPreRelease: true
          assets: '$(Build.ArtifactStagingDirectory)/*.apk'
  - job: iOS_App
    pool: 
      vmImage: 'macOS-10.14'
    steps:
      - task: UseDotNet@2
        displayName: 'Use .NET Core 3.x'
        inputs:
          packageType: sdk
          version: 3.x
          installationPath: $(Agent.ToolsDirectory)/dotnet
      - script: |
          dotnet tool install --global boots
      - script: |
          boots https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/xcode10.3/72cb587a39c12dfaa20cd5a0b1eb60a908ff88a6/1/package/xamarin.ios-12.14.0.113.pkg
      - script: |
          boots https://download.mono-project.com/archive/6.0.0/macos-10-universal/MonoFramework-MDK-6.0.0.313.macos10.xamarin.universal.pkg
      - task: XamariniOS@2
        displayName: 'Build iOS App'
        inputs:
          clean: true
          solutionFile: '**/*.sln'
          configuration: '$(buildConfiguration)'
          packageApp: false
          buildForSimulator: true
          runNugetRestore: true
         #args: # Optional
         #workingDirectory: # Optional
         #mdtoolFile: # Optional
         #signingIdentity: # Optional
         #signingProvisioningProfileID: # Optional