variables:
  buildConfiguration: 'Release'
  outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'

stages:
- stage: Build
  jobs:
    - job: 'Android'
    steps:
      - task: NuGetToolInstaller@1

      - task: NuGetCommand@2
        inputs:
          restoreSolution: '**/*.sln'

      - task: XamarinAndroid@1
        inputs:
          projectFile: '**/*Droid*.csproj'
          outputDirectory: '$(outputDirectory)'
          configuration: '$(buildConfiguration)'
          msbuildVersionOption: '16.0'
    - job: 'iOS'
    steps:
    - task: XamariniOS@2
      inputs:
        solutionFile: '**/*iOS.csproj'
        configuration: '$(buildConfiguration)'
        packageApp: false
        buildForSimulator: true