trigger:
- master
- develop
variables:
  buildConfiguration: 'Release'
  collNotesRepoName: 'j-h-m/collNotes'
  MonoVersion: '5_16_0'
  xcodeRoot: '/Applications/Xcode_10.1.app'
  apkFileName: 'com.thc.collnotes.apk'

stages:
- stage: Build_Test
  jobs:
    - job: 'Android_Build'
      pool:
        vmImage: 'windows-2019'
      steps:
      - task: NuGetToolInstaller@0
        displayName: 'install nuget tool'
        inputs:
          versionSpec: '5.x'
          checkLatest:  true
      - task: NuGetCommand@2
        displayName: 'nuget restore on solution'
        inputs:
          restoreSolution: '**/*.sln'
      - task: XamarinAndroid@1
        displayName: 'build app'
        inputs:
          clean: true
          projectFile: '**/*droid*.csproj'
          outputDirectory: '$(Build.ArtifactStagingDirectory)'
          configuration: '$(buildConfiguration)'
          createAppPackage: true
      - task: PublishPipelineArtifact@1
        displayName: 'publish apk'
        inputs:
          path: $(Build.ArtifactStagingDirectory)/$(apkFileName)
          artifact: android-apk