trigger:
- master
- topic-collNotes-v2
variables:
  buildConfiguration: 'Release'
  outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'
  createAppPackage: true
  collNotesRepoName: 'j-h-m/collNotes'
  preRelease: true

stages:
- stage: Build
  jobs:
  - job: Android_App
    pool:
      vmImage: 'windows-latest'
    steps:
      - task: NuGetToolInstaller@1
        inputs:
          versionSpec: '5.x'
          checkLatest: true
      - task: NuGetCommand@2
        inputs:
          restoreSolution: '**/*.sln'
      - task: DotNetCoreCLI@2
        inputs:
          command: test
          projects: '**/*Tests/*.csproj'
          arguments: '--configuration $(buildConfiguration)'
      - task: XamarinAndroid@1
        inputs:
          clean: true
          projectFile: '**/*droid*.csproj'
          outputDirectory: '$(outputDirectory)'
          configuration: '$(buildConfiguration)'
          createAppPackage: '$(createAppPackage)'
      - task: AndroidSigning@3
        inputs:
          apkFiles: '**/*.apk'
          apksignerKeystoreFile: '$(keyStoreFile)'
          apksignerKeystorePassword: '$(apkSignerKeystorePassword)'
          apksignerKeystoreAlias: '$(keyStoreAlias)'
          apksignerKeyPassword: '$(keyPassword)'
- stage: Github_Release
  jobs:
  - job: Android_APK
    steps:
      - task: GitHubRelease@1
        inputs:
          gitHubConnection: 'j-h-m'
          repositoryName: '$(collNotesRepoName)'
          action: 'create'
          tag: 'v2.x'
          tagSource: 'gitTag'
          title: 'test apk release'
          isPreRelease: '$(preRelease)'
          assets: '$(Build.ArtifactStagingDirectory)/*.apk'
