trigger:
- master
- topic-collNotes-v2
variables:
  buildConfiguration: 'Release'
  collNotesRepoName: 'j-h-m/collNotes'

stages:
- stage: Build
  jobs:
  - job: Android_App
    pool:
      vmImage: 'windows-latest'
    steps:
      - task: NuGetToolInstaller@1
        inputs:
          versionSpec: '5.x'
          checkLatest: true
      - task: NuGetCommand@2
        inputs:
          restoreSolution: '**/*.sln'
      - task: DotNetCoreCLI@2
        inputs:
          command: test
          projects: '**/*Tests/*.csproj'
          arguments: '--configuration $(buildConfiguration)'
      - task: XamarinAndroid@1
        inputs:
          clean: true
          projectFile: '**/*droid*.csproj'
          outputDirectory: '$(Build.ArtifactStagingDirectory)'
          configuration: '$(buildConfiguration)'
          createAppPackage: true
      - task: AndroidSigning@3
        inputs:
          apkFiles: '**/*.apk'
          apksignerKeystoreFile: 'ad-hoc jacob.keystore'
          apksignerKeystorePassword: '$(apkSignerKeystorePassword)'
          apksignerKeystoreAlias: '$(keyStoreAlias)'
          apksignerKeyPassword: '$(keyPassword)'
      - task: GitHubRelease@1
        inputs:
          gitHubConnection: 'j-h-m'
          repositoryName: '$(collNotesRepoName)'
          action: 'create'
          tag: 'v2.x'
          tagSource: 'gitTag'
          title: 'test apk release'
          isPreRelease: true
          assets: '$(Build.ArtifactStagingDirectory)/*.apk'
  - job: iOS_App
    pool: 'macOS-latest'
    steps:
      - task: XamariniOS@2
        inputs:
          clean: true
          solutionFile: '**/*.sln'
          configuration: '$(buildConfiguration)'
          packageApp: false
          buildForSimulator: true
          runNugetRestore: true
         #args: # Optional
         #workingDirectory: # Optional
         #mdtoolFile: # Optional
         #signingIdentity: # Optional
         #signingProvisioningProfileID: # Optional