stages:
- stage: Build
  jobs:
    - job: 'Android'
      pool:
        vmImage: 'windows-2019'
      variables:
        buildConfiguration: 'Release'
        outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'
      steps:
      - task: NuGetToolInstaller@1

      - task: NuGetCommand@2
        inputs:
          restoreSolution: '**/*.sln'

      - task: XamarinAndroid@1
        inputs:
          projectFile: '**/*droid*.csproj'
          outputDirectory: '$(outputDirectory)'
          configuration: '$(buildConfiguration)'
          msbuildVersionOption: '16.0'


    - job: 'iOS'
      steps:
      # https://docs.microsoft.com/azure/devops/pipelines/ecosystems/xamarin
      pool:
        vmImage: 'macOS-10.15' # For Windows, use 'windows-2019'
      # To manually select a Xamarin SDK version on the Hosted macOS agent, enable this script with the SDK version you want to target
      # https://go.microsoft.com/fwlink/?linkid=871629
      - script: sudo $AGENT_HOMEDIRECTORY/scripts/select-xamarin-sdk.sh 5_4_1 
        displayName: 'Select Xamarin SDK version'
        enabled: false

      - task: NuGetToolInstaller@1

      - task: NuGetCommand@2
        inputs:
          restoreSolution: '**/*.sln'

      - task: XamariniOS@2
        inputs:
          solutionFile: '**/*.sln'
          configuration: 'Release'
          buildForSimulator: true
          packageApp: false