trigger:
- master
- develop
variables:
  buildConfiguration: 'Release'
  collNotesRepoName: 'j-h-m/collNotes'
  MonoVersion: '5_16_0'
  xcodeRoot: '/Applications/Xcode_10.1.app'

stages:
- stage: Build_Test
  jobs:
    - job: 'Android'
      pool:
        vmImage: 'windows-latest'
      steps:
      - task: NuGetToolInstaller@0
        displayName: 'Install NuGet tool'
      - task: NuGetCommand@2
        displayName: 'nuget restore on solution'
        inputs:
          restoreSolution: '**/*.sln'
      - task: XamarinAndroid@1
        displayName: 'Build App'
        inputs:
          clean: true
          projectFile: '**/*droid*.csproj'
          outputDirectory: '$(Build.ArtifactStagingDirectory)'
          configuration: '$(buildConfiguration)'
          createAppPackage: true
      - task: PublishPipelineArtifact@1
        displayName: 'publish apk'
        inputs:
          path: $(Build.ArtifactStagingDirectory)/*.apk
          artifact: android-apk